import { Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography variant="h1">DevALMO, YouTube channel</Typography>
        <Link
          href={{
            pathname: "/receiveData",
            query: {
              id: 37,
              title: "lorem",
            },
          }}
        >
          Receive Data
        </Link>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
